
services:

  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: loanManagementSystem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Deep@nsh.98
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis
  redis:
    image: redis:7-alpine

    ports:
      - "6379:6379"

  # Spring Boot Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/loanManagementSystem
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Deep@nsh.98
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      GROQ_API_KEY: ${GROQ_API_KEY}
    depends_on:
      - postgres
      - redis

  # React Frontend
  frontend:
    build: 
      context: ./loan-ui
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:8080  
    ports:
      - "3000:80"
    depends_on:
      - backend

  # docker-compose.yml — add these services

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana-data:/var/lib/grafana
    restart: always 

volumes:
  postgres_data:
  grafana-data:

configs:
  prometheus_config:
    content: |
      global:
        scrape_interval: 15s
      scrape_configs:
        - job_name: 'loan-management-system'
          static_configs:
            - targets: ['backend:8080']
          metrics_path: '/actuator/prometheus' 
          scheme: http
        - job_name: 'loan-railway'
          static_configs:
            - targets: ['loanmanagementsystem.up.railway.app']
          metrics_path: '/actuator/prometheus'
          scheme: https
        