# # Enable prometheus
# management.prometheus.metrics.export.enabled=true

# # Pushgateway address
# management.prometheus.metrics.export.pushgateway.address=https://prometheus-prod-43-prod-ap-south-1.grafana.net/api/prom

# # Username (your Instance ID)
# management.prometheus.metrics.export.pushgateway.username=3149652

# # Password (your API token)
# management.prometheus.metrics.export.pushgateway.password=${GRAFANA_API_TOKEN}

# # Enable pushgateway
# management.prometheus.metrics.export.pushgateway.enabled=true

# # Job name
# management.prometheus.metrics.export.pushgateway.job=loan-management-system

# # Push every 15 seconds
# management.prometheus.metrics.export.pushgateway.push-rate=15s