spring.application.name=LoanManagementSystem2

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/loanManagementSystem
spring.datasource.username=postgres
spring.datasource.password=Deep@nsh.98
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret="Hi there I am secret key for this project Loan Management System"
jwt.expiration=86400000

# Anthropic API Key
anthropic.api.key=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

# Groq API Key
groq.api.key=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